export const MAX_STAT_LEVEL = 99;
export const WEAPON_STATS_NAMES = ["strength", "dexterity", "intelligence", "faith", "arcane"];
export const STAT_NAMES = ["vigor", "mind", "endurance", "strength", "dexterity", "intelligence", "faith", "arcane"];
export const ATTACK_TYPES = ["physical", "magic", "fire", "lightning", "holy"];
export const NEGATION_NAMES = ["physical", "strike", "slash", "pierce", "magic", "fire", "lightning", "holy"];
export const PHYSICAL_DEFENCE_NAMES = ["Physical", "VS Strike", "VS Slash", "VS Pierce"]
export const MAGIC_DEFENCE_NAMES = ["Magic", "Fire", "Lightning", "Holy"]
export const RESISTANCE_NAMES = ["Immunity", "Robustness", "Focus", "Vitality"]
export const ARMOUR_TYPES = ["Helmet", "Chest", "Gauntlets", "Legs"]
export const SORT_OPTIONS = ["trending", "mostviewed", "latest"]